<link rel="stylesheet" type="text/css" href="../css/datatables.min.css">
<link rel="stylesheet" type="text/css" href="../css/modal.css">
<link rel="stylesheet" type="text/css" href="../css/variable.css">
<link rel="stylesheet" type="text/css" href="../css/ui_styles.css">
<link rel="stylesheet" type="text/css" href="../css/main.css">
<link rel="stylesheet" type="text/css" href="../css/login.css">
<link rel="stylesheet" type="text/css" href="../css/admin/admin-login.css">
<link rel="stylesheet" type="text/css" href="../css/admin/admin-sidebar.css">
<link rel="stylesheet" type="text/css" href="../css/admin/admin-edit-product.css">